load Rails.root.join('db/seeds/data/users_seed.rb')
load Rails.root.join('db/seeds/data/tags_seed.rb')
load Rails.root.join('db/seeds/data/decisions_seed.rb')
load Rails.root.join('db/seeds/data/decision_tags.rb')
load Rails.root.join('db/seeds/data/conversations_seed.rb')
load Rails.root.join('db/seeds/data/character_responses_seed.rb')
load Rails.root.join('db/seeds/data/comments_seed.rb')
load Rails.root.join('db/seeds/data/bookmarks_seed.rb')